import { Nav } from "@components";
import "./globals.css";
import { Inter } from "next/font/google";
import { StateContext } from "@context/StateContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Moncef Boutique",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StateContext>
        <body
          className={`${inter.className} app`}
          suppressHydrationWarning={true}
        >
          <Nav />
          {children}
        </body>
      </StateContext>
    </html>
  );
}
